#!/bin/sh
set -eu

ORIGINAL_DATABASE_URL="${DATABASE_URL-}"
ORIGINAL_REDIS_URL="${REDIS_URL-}"
ORIGINAL_CLICKHOUSE_URL="${CLICKHOUSE_URL-}"
ORIGINAL_CLICKHOUSE_DATABASE="${CLICKHOUSE_DATABASE-}"
ORIGINAL_BETTER_AUTH_SECRET="${BETTER_AUTH_SECRET-}"
ORIGINAL_BETTER_AUTH_URL="${BETTER_AUTH_URL-}"
ORIGINAL_NEXT_PUBLIC_APP_URL="${NEXT_PUBLIC_APP_URL-}"
ORIGINAL_GOOGLE_API_KEY="${GOOGLE_API_KEY-}"
ORIGINAL_LOG_LEVEL="${LOG_LEVEL-}"
ORIGINAL_ENABLE_TEST_AUTH="${ENABLE_TEST_AUTH-}"

if [ -f ./.env ]; then
  set -a
  . ./.env
  set +a
fi

export PORT="${PORT:-3000}"
export NODE_ENV="${NODE_ENV:-development}"
if [ -n "$ORIGINAL_DATABASE_URL" ]; then export DATABASE_URL="$ORIGINAL_DATABASE_URL"; fi
if [ -n "$ORIGINAL_REDIS_URL" ]; then export REDIS_URL="$ORIGINAL_REDIS_URL"; fi
if [ -n "$ORIGINAL_CLICKHOUSE_URL" ]; then export CLICKHOUSE_URL="$ORIGINAL_CLICKHOUSE_URL"; fi
if [ -n "$ORIGINAL_CLICKHOUSE_DATABASE" ]; then export CLICKHOUSE_DATABASE="$ORIGINAL_CLICKHOUSE_DATABASE"; fi
if [ -n "$ORIGINAL_BETTER_AUTH_SECRET" ]; then export BETTER_AUTH_SECRET="$ORIGINAL_BETTER_AUTH_SECRET"; fi
if [ -n "$ORIGINAL_BETTER_AUTH_URL" ]; then export BETTER_AUTH_URL="$ORIGINAL_BETTER_AUTH_URL"; fi
if [ -n "$ORIGINAL_NEXT_PUBLIC_APP_URL" ]; then export NEXT_PUBLIC_APP_URL="$ORIGINAL_NEXT_PUBLIC_APP_URL"; fi
if [ -n "$ORIGINAL_GOOGLE_API_KEY" ]; then export GOOGLE_API_KEY="$ORIGINAL_GOOGLE_API_KEY"; fi
if [ -n "$ORIGINAL_LOG_LEVEL" ]; then export LOG_LEVEL="$ORIGINAL_LOG_LEVEL"; fi
if [ -n "$ORIGINAL_ENABLE_TEST_AUTH" ]; then export ENABLE_TEST_AUTH="$ORIGINAL_ENABLE_TEST_AUTH"; fi
export ENABLE_TEST_AUTH="${ENABLE_TEST_AUTH:-true}"
export BETTER_AUTH_SECRET="${BETTER_AUTH_SECRET:-test-secret-at-least-32-characters-long}"
export BETTER_AUTH_URL="${BETTER_AUTH_URL:-http://127.0.0.1:3000}"
export NEXT_PUBLIC_APP_URL="${NEXT_PUBLIC_APP_URL:-http://127.0.0.1:3000}"
export GOOGLE_API_KEY="${GOOGLE_API_KEY:-test-key}"
export LOG_LEVEL="${LOG_LEVEL:-warn}"

exec pnpm --filter web exec next dev --hostname 127.0.0.1 --port "$PORT"
